# Generated by Django 5.2 on 2025-04-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='total_harga',
            field=models.BigIntegerField(),
        ),
    ]
