# Generated by Django 4.2.10 on 2025-04-27 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_transaksi_total_harga'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateTimeField(auto_now=True)),
                ('forecast_data', models.JSONField()),
                ('reorder_point', models.FloatField()),
                ('expected_demand', models.FloatField()),
                ('days_until_stockout', models.IntegerField()),
                ('lead_time', models.IntegerField(default=7)),
                ('stok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stok')),
            ],
            options={
                'ordering': ['-prediction_date'],
            },
        ),
    ]
