# Generated by Django 4.2.10 on 2025-04-27 16:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_stockprediction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockprediction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Prediksi Stok', 'verbose_name_plural': 'Prediksi Stok'},
        ),
        migrations.RemoveField(
            model_name='stockprediction',
            name='forecast_data',
        ),
        migrations.RemoveField(
            model_name='stockprediction',
            name='prediction_date',
        ),
        migrations.RemoveField(
            model_name='stockprediction',
            name='stok',
        ),
        migrations.AddField(
            model_name='stockprediction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tanggal Dibuat'),
        ),
        migrations.AddField(
            model_name='stockprediction',
            name='forecast_dates',
            field=models.TextField(default=1, verbose_name='Tanggal Prediksi (JSON)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockprediction',
            name='forecast_values',
            field=models.TextField(default=1, verbose_name='Nilai Prediksi (JSON)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockprediction',
            name='plot_data',
            field=models.TextField(default=1, verbose_name='Data Plot (Base64)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockprediction',
            name='prediction_days',
            field=models.IntegerField(default=30, verbose_name='Periode Prediksi (hari)'),
        ),
        migrations.AddField(
            model_name='stockprediction',
            name='stok_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.stok', verbose_name='Produk'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockprediction',
            name='days_until_stockout',
            field=models.IntegerField(verbose_name='Hari Hingga Habis'),
        ),
        migrations.AlterField(
            model_name='stockprediction',
            name='expected_demand',
            field=models.FloatField(verbose_name='Perkiraan Permintaan'),
        ),
        migrations.AlterField(
            model_name='stockprediction',
            name='lead_time',
            field=models.IntegerField(default=7, verbose_name='Lead Time (hari)'),
        ),
        migrations.AlterField(
            model_name='stockprediction',
            name='reorder_point',
            field=models.FloatField(verbose_name='Titik Pemesanan Ulang'),
        ),
    ]
