# Generated by Django 5.0.3 on 2025-05-27 17:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_stockprediction_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockPredictionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prediction_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("current_stock", models.FloatField(default=0)),
                ("forecast_data", models.TextField()),
                ("reorder_point", models.FloatField(default=0)),
                ("expected_demand", models.FloatField(default=0)),
                ("days_until_stockout", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="app.stok",
                    ),
                ),
            ],
            options={
                "ordering": ["-prediction_date"],
            },
        ),
        migrations.DeleteModel(
            name="StockPrediction",
        ),
        migrations.AddIndex(
            model_name="stockpredictionresult",
            index=models.Index(
                fields=["product", "prediction_date"],
                name="app_stockpr_product_d431bd_idx",
            ),
        ),
    ]
