# Generated by Django 5.2 on 2025-07-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_stockpredictionresult_delete_stockprediction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockpredictionresult",
            name="lead_time",
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name="stockpredictionresult",
            name="prediction_days",
            field=models.IntegerField(default=30),
        ),
    ]
