# Generated by Django 5.0.3 on 2025-04-15 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stok",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nama", models.CharField(max_length=100)),
                ("kategori", models.CharField(max_length=100)),
                ("harga", models.IntegerField()),
                ("stok", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Transaksi",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("qty", models.IntegerField()),
                ("total_harga", models.IntegerField()),
                ("tanggal_transaksi", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stok_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.stok",
                    ),
                ),
            ],
        ),
    ]
